version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=db'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=123456'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=123456'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_EXTERNALSECURE=false'
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: 'service_healthy'

  db:
    image: postgres:16
    restart: always
    networks:
      - 'zitadel'
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=zitadel
    volumes:
      - ./dataset-zitadel:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'zitadel', '-U', 'postgres']
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

  zstarter-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=zstarter

    volumes:
      - ./dataset-zstarter:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432

networks:
  zitadel:
