version: '3.1'
services:
  db:
    image: postgres:16
    restart: always
    networks:
      - 'zitadel'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=zitadel
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432

networks:
  zitadel:
    external: true

